### ISSUE TITLE
Infinite loop in generating TimestreamQuery operations

### ISSUE THREAD

**Issue by GrahamCampbell** [async-aws/aws#1209]
```
PHP Fatal error:  Uncaught Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames in /data/src/CodeGenerator/src/Definition/StructureMember.php:20
Stack trace:
#0 /data/src/CodeGenerator/src/Definition/StructureMember.php(11): AsyncAws\CodeGenerator\Definition\StructureMember->getOwnerShape()
#1 /data/src/CodeGenerator/src/Definition/ServiceDefinition.php(152): AsyncAws\CodeGenerator\Definition\StructureMember->getName()
#2 /data/src/CodeGenerator/src/Definition/ServiceDefinition.php(168): AsyncAws\CodeGenerator\Definition\ServiceDefinition->getShape()
#3 /data/src/CodeGenerator/src/Definition/Member.php(27): AsyncAws\CodeGenerator\Definition\ServiceDefinition->AsyncAws\CodeGenerator\Definition\{closure}()
#4 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(126): AsyncAws\CodeGenerator\Definition\Member->getShape()
#5 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(183): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->getInputAccessorName()
#6 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(152): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseResponseStructure()
#7 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(183): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseElement()
#8 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(152): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseResponseStructure()
...
#236 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(152): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseResponseStructure()
#237 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(183): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseElement()
#238 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(152): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseResponseStructure()
#239 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(284): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseElement()
#240 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(150): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseResponseList()
#241 /data/src/CodeGenerator/src/Generator/ResponseParser/RestJsonParser.php(68): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->parseElement()
#242 /data/src/CodeGenerator/src/Generator/CodeGenerator/PopulatorGenerator.php(244): AsyncAws\CodeGenerator\Generator\ResponseParser\RestJsonParser->generate()
#243 /data/src/CodeGenerator/src/Generator/CodeGenerator/PopulatorGenerator.php(70): AsyncAws\CodeGenerator\Generator\CodeGenerator\PopulatorGenerator->generatePopulator()
#244 /data/src/CodeGenerator/src/Generator/ResultGenerator.php(88): AsyncAws\CodeGenerator\Generator\CodeGenerator\PopulatorGenerator->generate()
#245 /data/src/CodeGenerator/src/Generator/ResultGenerator.php(67): AsyncAws\CodeGenerator\Generator\ResultGenerator->generateResultClass()
#246 /data/src/CodeGenerator/src/Generator/OperationGenerator.php(120): AsyncAws\CodeGenerator\Generator\ResultGenerator->generate()
#247 /data/src/CodeGenerator/src/Command/GenerateCommand.php(273): AsyncAws\CodeGenerator\Generator\OperationGenerator->generate()
#248 /data/src/CodeGenerator/src/Command/GenerateCommand.php(151): AsyncAws\CodeGenerator\Command\GenerateCommand->generateService()
#249 /data/src/CodeGenerator/src/Command/GenerateCommand.php(88): AsyncAws\CodeGenerator\Command\GenerateCommand->generateServicesSequential()
#250 /data/vendor/symfony/console/Command/Command.php(298): AsyncAws\CodeGenerator\Command\GenerateCommand->execute()
#251 /data/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#252 /data/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#253 /data/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#254 /data/src/CodeGenerator/generate.php(21): Symfony\Component\Console\Application->run()
#255 /data/generate(32): require('...')
#256 {main}
  thrown in /data/src/CodeGenerator/src/Definition/StructureMember.php on line 20
```

I added a `echo "$input\n";` into `parseElement` to see what's going on...

```
$data['QueryId']
$data['NextToken']
$data['Rows']
$item
$item['Data']
$item
$item['ScalarValue']
$item['TimeSeriesValue']
$item
$item['Time']
$item['Value']
$item['Value']['ScalarValue']
$item['Value']['TimeSeriesValue']
$item['Value']['ArrayValue']
$item['Value']['RowValue']
$item['Value']['RowValue']['Data']
$item['Value']['NullValue']
$item['ArrayValue']
$item['RowValue']
$item['RowValue']['Data']
$item['NullValue']
$data['ColumnInfo']
$item
$item['Name']
$item['Type']
$item['Type']['ScalarType']
$item['Type']['ArrayColumnInfo']
$item['Type']['ArrayColumnInfo']['Name']
$item['Type']['ArrayColumnInfo']['Type']
$item['Type']['ArrayColumnInfo']['Type']['ScalarType']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Name']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ScalarType']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Name']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ScalarType']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Name']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ScalarType']
$item['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']['Type']['ArrayColumnInfo']
...
```

**Comment by GrahamCampbell** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/2829600/161455405-48953f86-b200-4343-ae0d-9ff1669a2736.png">
