### ISSUE TITLE
DynamoDB query not working with ExclusiveStartKey

### ISSUE THREAD

**Issue by hassaan-dev** [async-aws/aws#1578]
Hi,

I am using `query` to find the records inside `Index`. This is working fine But I have minimum 200+ records against the condition using for query.

For best practices and improve response time, I need to use paging as number of records that can be 500 or 1000 or higher.

I find that DynamoDB support `cursor` paging so I have to send last record's `id` for next page. `ExclusiveStartKey` is used for this.

**Error**

```
{
    "errorType": "AsyncAws\\Core\\Exception\\Http\\ClientException",
    "errorMessage": "HTTP 400 returned for \"https://dynamodb.eu-west-1.amazonaws.com/\".\n\nCode: SerializationException\nMessage: Unrecognized collection type class com.amazonaws.dynamodb.v20120810.AttributeValue\nType: \nDetail: \n",
    "stack": [
        "#0 /var/task/vendor/async-aws/core/src/Response.php(446): AsyncAws\\Core\\Response::AsyncAws\\Core\\{closure}()",
        "#1 /var/task/vendor/async-aws/core/src/Response.php(179): AsyncAws\\Core\\Response->getResolveStatus()",
        "#2 /var/task/vendor/async-aws/core/src/Result.php(69): AsyncAws\\Core\\Response->resolve(NULL)",
        "#3 /var/task/vendor/async-aws/core/src/Result.php(137): AsyncAws\\Core\\Result->resolve()",
        "#4 /var/task/vendor/async-aws/dynamo-db/src/Result/QueryOutput.php(79): AsyncAws\\Core\\Result->initialize()",
        "#5 /var/task/src/Service/DynamoDBHandler.php(35): AsyncAws\\DynamoDb\\Result\\QueryOutput->getCount()"
    ]
}

```

**Query**

```
{
    "TableName": "logs",
    "KeyConditions": {
        "user_id": {
            "AttributeValueList": [
                {
                    "S": "123"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    },
    "IndexName": "user_id-index",
    "ScanIndexForward": false,
    "Limit": 2,
    "ExclusiveStartKey": {
        "id": {
            "AttributeValueList": [
                {
                    "S": "abc2"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    }
}

```

This is not the only query I have tried with, I have also tried it with invalid query and got invalid `ExclusiveStartKey` error which make sense.

Other queries I have tried are following

**Query 2 **

```
{
    "TableName": "logs",
    "KeyConditions": {
        "user_id": {
            "AttributeValueList": [
                {
                    "S": "123"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    },
    "IndexName": "user_id-index",
    "ScanIndexForward": false,
    "Limit": 2,
    "ExclusiveStartKey": {
        "id": {
            "AttributeValueList": [
                {
                    "S": "abc2"
                }
            ],
            "ComparisonOperator": "EQ"
        },
        "user_id": {
            "AttributeValueList": [
                {
                    "S": "123"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    }
}

```

**Query 3 **

```
{
    "TableName": "logs",
    "KeyConditions": {
        "user_id": {
            "AttributeValueList": [
                {
                    "S": "123"
                }
            ],
            "ComparisonOperator": "EQ"
        }
    },
    "IndexName": "user_id-index",
    "ScanIndexForward": false,
    "Limit": 2,
    "ExclusiveStartKey": {
        "id": {
                    "S": "abc2"
                }
        }
    }
}

```

Can someone quide me, where I am wrong here?

**Comment by GrahamCampbell** [comment]
This was fixed by https://github.com/async-aws/aws/pull/1565.
