### ISSUE TITLE
Issue with Symfony Cache Adapter

### ISSUE THREAD

**Issue by TamasSzigeti** [async-aws/aws#891]
Hi, thanks for the awesome package(s)!

I found a small thing that's worth mentioning.
Normally, when using symfony cache, and there is an error, it doesn't break the app, it just gives a warning log that reading or writing a key has failed. Now when I use a broken cache adapter (e.g. unreachable redis) with async-aws credential cache, then the exception propagates all the way and causes a hard break instead of a warning.

I believe it would be worth following a similar pattern and make the cache optional – allow it to error without breaking the flow.

**Comment by Nyholm** [comment]
I've looked the the PSR6 cache adapter. I cannot see how or why a cache miss would fail. Could you share some exception, stack trace or code sample?

**Comment by TamasSzigeti** [comment]
It's not a cache miss, it's a non-accessible cache provider. Here's the stack trace, hope it helps:

```
Symfony\Component\Cache\Exception\InvalidArgumentException: Redis connection "redis://redis" failed: php_network_getaddresses: getaddrinfo failed: Name or service not known
#39 /vendor/symfony/cache/Traits/RedisTrait.php(201): Symfony\Component\Cache\Adapter\RedisAdapter::Symfony\Component\Cache\Traits\{closure}
#38 /vendor/symfony/cache/Traits/RedisProxy.php(33): Closure::__invoke
#37 /vendor/symfony/cache/Traits/RedisProxy.php(33): Symfony\Component\Cache\Traits\RedisProxy::__call
#36 /vendor/symfony/cache/Traits/RedisTrait.php(402): Symfony\Component\Cache\Adapter\RedisAdapter::doDelete
#35 /vendor/symfony/cache/Adapter/AbstractAdapter.php(155): Symfony\Component\Cache\Adapter\AbstractAdapter::commit
#34 /vendor/symfony/cache/Traits/AbstractAdapterTrait.php(267): Symfony\Component\Cache\Adapter\AbstractAdapter::save
#33 /vendor/symfony/cache-contracts/CacheTrait.php(72): Symfony\Component\Cache\Adapter\AbstractAdapter::doGet
#32 /vendor/symfony/cache/Traits/ContractsTrait.php(95): Symfony\Component\Cache\Adapter\AbstractAdapter::doGet
#31 /vendor/symfony/cache-contracts/CacheTrait.php(33): Symfony\Component\Cache\Adapter\AbstractAdapter::get
#30 /vendor/symfony/cache/Adapter/ChainAdapter.php(103): Symfony\Component\Cache\Adapter\ChainAdapter::Symfony\Component\Cache\Adapter\{closure}
#29 /vendor/symfony/cache/LockRegistry.php(99): Symfony\Component\Cache\LockRegistry::compute
#28 /vendor/symfony/cache/Traits/ContractsTrait.php(88): Symfony\Component\Cache\Adapter\AbstractAdapter::Symfony\Component\Cache\Traits\{closure}
#27 /vendor/symfony/cache-contracts/CacheTrait.php(70): Symfony\Component\Cache\Adapter\AbstractAdapter::doGet
#26 /vendor/symfony/cache/Traits/ContractsTrait.php(95): Symfony\Component\Cache\Adapter\AbstractAdapter::doGet
#25 /vendor/symfony/cache-contracts/CacheTrait.php(33): Symfony\Component\Cache\Adapter\AbstractAdapter::get
#24 /vendor/symfony/cache/Adapter/ChainAdapter.php(103): Symfony\Component\Cache\Adapter\ChainAdapter::Symfony\Component\Cache\Adapter\{closure}
#23 /vendor/symfony/cache/Adapter/ChainAdapter.php(114): Symfony\Component\Cache\Adapter\ChainAdapter::get
#22 /vendor/async-aws/core/src/Credentials/SymfonyCacheProvider.php(44): AsyncAws\Core\Credentials\SymfonyCacheProvider::getCredentials
#21 /vendor/async-aws/core/src/Credentials/CacheProvider.php(35): AsyncAws\Core\Credentials\CacheProvider::getCredentials
#20 /vendor/async-aws/core/src/AbstractApi.php(122): AsyncAws\Core\AbstractApi::getResponse
#19 /vendor/async-aws/dynamo-db/src/DynamoDbClient.php(229): AsyncAws\DynamoDb\DynamoDbClient::getItem
#18 /vendor/async-aws/dynamo-db-session/src/SessionHandler.php(142): AsyncAws\DynamoDbSession\SessionHandler::read
#17 /vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php(59): Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy::read
#16 [internal](0): session_start
#15 /vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(156): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage::start
#14 /vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(323): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage::getBag
#13 /vendor/symfony/http-foundation/Session/Session.php(257): Symfony\Component\HttpFoundation\Session\Session::getBag
#12 /vendor/symfony/http-foundation/Session/Session.php(279): Symfony\Component\HttpFoundation\Session\Session::getAttributeBag
#11 /vendor/symfony/http-foundation/Session/Session.php(83): Symfony\Component\HttpFoundation\Session\Session::set
#10 /vendor/symfony/security-http/Util/TargetPathTrait.php(28): Symfony\Component\Security\Http\Firewall\ExceptionListener::saveTargetPath
#9 /vendor/symfony/security-http/Firewall/ExceptionListener.php(237): Symfony\Component\Security\Http\Firewall\ExceptionListener::setTargetPath
#8 /vendor/symfony/security-http/Firewall/ExceptionListener.php(210): Symfony\Component\Security\Http\Firewall\ExceptionListener::startAuthentication
#7 /vendor/symfony/security-http/Firewall/ExceptionListener.php(151): Symfony\Component\Security\Http\Firewall\ExceptionListener::handleAccessDeniedException
#6 /vendor/symfony/security-http/Firewall/ExceptionListener.php(102): Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException
#5 /vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#4 /vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#3 /vendor/symfony/http-kernel/HttpKernel.php(218): Symfony\Component\HttpKernel\HttpKernel::handleThrowable
#2 /vendor/symfony/http-kernel/HttpKernel.php(90): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/http-kernel/Kernel.php(196): Symfony\Component\HttpKernel\Kernel::handle
#0 /public/index.php(28): null
```

**Comment by TamasSzigeti** [comment]
Seems it does, and I was going to offer creating a PR as well, thanks for the quick response (: I'll add my comments there
