### ISSUE TITLE
Throwing exception twice because of Waiter destructor

### ISSUE THREAD

**Issue by sunkan** [async-aws/aws#927]
Hi 

I'm have a problem where this code throws exception twice.

I saw that you solved something similar to this with #171

So I assume this a bug.

### script

```php
<?php declare(strict_types=1);

include 'vendor/autoload.php';

function testExceptions() {
	$s3 = new \AsyncAws\S3\S3Client([
		'endpoint' => 'http://127.0.0.1:9000'
	]);
	try {
		$result = $s3->bucketExists([
			'Bucket' => 'test'
		]);

		return $result->isSuccess();
	}
	catch (\Throwable $e) {
		var_dump('caught exception: ' . get_class($e));
	}
	return false;
}

var_dump(testExceptions());
```

### expected output should be
```
string(63) "caught exception: AsyncAws\Core\Exception\Http\NetworkException"
bool(false)
```

### now it's
```
string(63) "caught exception: AsyncAws\Core\Exception\Http\NetworkException"
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\TransportException: Couldn't connect to server for "http://127.0.0.1:9000/test". in /opt/projects/experiments/async-aws-exception/vendor/symfony/http-client/Response/CurlResponse.php:317
Stack trace:
#0 /opt/projects/experiments/async-aws-exception/vendor/symfony/http-client/Response/TransportResponseTrait.php(170): Symfony\Component\HttpClient\Response\CurlResponse::perform()
#1 [internal function]: Symfony\Component\HttpClient\Response\CurlResponse::stream()
#2 /opt/projects/experiments/async-aws-exception/vendor/symfony/http-client/Response/ResponseStream.php(47): Generator->rewind()
#3 /opt/projects/experiments/async-aws-exception/vendor/symfony/http-client/Response/AsyncResponse.php(250): Symfony\Component\HttpClient\Response\ResponseStream->rewind()
#4 /opt/projects/experiments/async-aws-exception/vendor/symfony/http-client/Response/AsyncResponse.php(63): Symfony\Component\HttpClient\Response\AsyncResponse::stream()
#5 /opt/projects/experiments/async-aws-exception/vendor/symfony/http-client/Response/CommonResponseTrait.php(152): Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}()
#6 /opt/projects/experiments/async-aws-exception/vendor/symfony/http-client/Response/AsyncResponse.php(90): Symfony\Component\HttpClient\Response\AsyncResponse::initialize()
#7 /opt/projects/experiments/async-aws-exception/vendor/async-aws/core/src/Response.php(109): Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
#8 /opt/projects/experiments/async-aws-exception/vendor/async-aws/core/src/Waiter.php(90): AsyncAws\Core\Response->resolve()
#9 /opt/projects/experiments/async-aws-exception/vendor/async-aws/core/src/Waiter.php(66): AsyncAws\Core\Waiter->getState()
#10 /opt/projects/experiments/async-aws-exception/test.php(15): AsyncAws\Core\Waiter->isSuccess()
#11 /opt/projects/experiments/async-aws-exception/test.php(23): testExceptions()
#12 {main}
```

**Comment by jderusse** [comment]
Hey, 

Looks like this is a bug. Let me time to check and fix it.

**Comment by jderusse** [comment]
please, have a look to #928

**Comment by sunkan** [comment]
Yes this works. 

Thanks for the quick response
